[project]
name = "english-station"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.16.2",
    "django>=6.1.1",
    "django-allauth>=65.19.7",
    "django-stubs>=6.1.1",
]

[dependency-groups]
dev = [
    "ruff>=0.17.0",
]

[[tool.mypy.overrides]]
module = "app_english.models"
ignore_errors = true

[tool.ruff.lint]
extend-select = [
    "DJ",       # flake8-django: Django-specific bugs
    "E",        # pycodestyle errors
    "F",        # Pyflakes
    "W",        # pycodestyle warnings
    "I",        # isort
    "UP",       # pyupgrade
    "B",        # flake8-bugbear
]
